name: Builb Test and push
on: [push]
env:
  IMAGE_NAME: user_service
  REPO_NAME: abood1


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
       docker build ./user -t ${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }} -f Dockerfile
    - name: run docker
      id: run-docker
      working-directory: .
      run: |
        docker run -d -e 8080:8080 -host=172.17.0.2 $REPO_NAME/$IMAGE_NAME:latest && \
          docker ps && sleep 5
   

    - name: Output summary to console
      working-directory: .
      run: echo ${{ steps.run-docker.outputs.summary }}


    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$IMAGE_NAME